[package]
name = "ikanago/omekasy"
version = "1.1.0"
description = "ğ˜¾ğ™¤ğ™¢ğ™¢ğ™–ğ™£ğ™™ ğ™¡ğ™ğ™£ğ™š ğ™–ğ™¥ğ™¥ğ™¡ğ™ğ™˜ğ™–ğ™©ğ™ğ™¤ğ™£ ğ•¥ğ•™ğ•’ğ•¥ ğ•”ğ• ğ•Ÿğ•§ğ•–ğ•£ğ•¥ğ•¤ ğ•’ğ•ğ•¡ğ•™ğ•’ğ•Ÿğ•¦ğ•ğ•–ğ•£ğ•šğ•” ğ•”ğ•™ğ•’ğ•£ğ•’ğ•”ğ•¥ğ•–ğ•£ğ•¤ ğ’•ğ’ ğ’—ğ’‚ğ’“ğ’Šğ’ğ’–ğ’” ğ’”ğ’•ğ’šğ’ğ’†ğ’” ğšğšğšğš’ğš—ğšğš ğš’ğš— ğš„ğš—ğš’ğšŒğš˜ğšğš."
license = "MIT"
repository = "https://github.com/ikanago/omekasy"
readme = "README.md"

[[module]]
name = "omekasy"
source = "target/wasm32-wasi/release/omekasy.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "omekasy"
module = "omekasy"
